# Generated by Django 5.2.9 on 2025-12-12 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_alter_cook_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(default=0, help_text='Enter the years of experience.', validators=[django.core.validators.MinValueValidator(0, message='Years Of Experience can`t be negative.'), django.core.validators.MaxValueValidator(40, message='Experience cannot exceed 40 years.')], verbose_name='Years of experience'),
        ),
    ]
